spring:
    profiles:
        active: test

kafka:
    bootstrap-servers: "localhost:29092"
    group_id: "kafka_demo"
    topic:
        input:
            genericInputTopic: "inputTopic"
        output:
            genericOutputTopic: "outputTopic"
